### ISSUE TITLE
feat: Offline availability

### ISSUE THREAD

**Issue by jo-gross** [jo-gross/Cocktail-Manager#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues and nothing seems to be related to my idea.

### Is your feature request related to a problem? Please describe. What is your idea?

If you have an instable internet connection, this app is not that useful, causing the missing option to track items. 
I wont expect an offline search for cocktails, but a cached card and the option to track cocktails offline would be very nice.

### Describe the solution you'd like. How should it look in the app?

Use the browsers cache to made the card and tracking still available.

**Comment by jo-gross** [comment]
As @LinusDierheimer recommended: service workers are the perfect match

**Comment by Resaki1** [comment]
What do you think about converting it to a [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)? In addition to better offline availability thanks to caching with service workers, users would be able to add the app to their homescreen, making it behave pretty much like a natively installed program. Is this something that'd be helpful, or are you only interested in offline availability?
