### ISSUE TITLE
feat: add checkbox to shopping list on calculation page

### ISSUE THREAD

**Issue by jhns-de** [jo-gross/Cocktail-Manager#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues and nothing seems to be related to my idea.

### Is your feature request related to a problem? Please describe. What is your idea?

It is quite difficult to keep a good overview of which ingredients were already purchased and which weren't in the shopping list in the calculation interface.

### Describe the solution you'd like. How should it look in the app?

A simple checkbox (which is also saved in the db) next to every ingredient in the shopping list. With this it would be possible to mark ingredients which are already purchased and make it easier to keep a good overview.

- [ ] A bonus feature would be if the checkbox is automatically unchecked as soon as the amount of this ingredient is changed (or even better increased).

**Comment by jo-gross** [comment]
As you mentioned some days ago, i also would add an csv export function within this feature
